apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
      - name: ingestion
        image: youracr.azurecr.io/ingestion:latest
        envFrom:
        - secretRef:
            name: azure-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
spec:
  selector:
    app: ingestion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: transformation-service
spec:
  selector:
    app: transformation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: load-sql-service
spec:
  selector:
    app: load-sql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000