name: Data Pipeline CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_CONTAINER_REGISTRY: youracr.azurecr.io
  RESOURCE_GROUP: your-resource-group
  AKS_CLUSTER: your-aks-cluster

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Ingestion Image
      working-directory: ./ingestion
      run: |
        docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/ingestion:latest .
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/ingestion:latest

    - name: Build and Push Transformation Image
      working-directory: ./transformation
      run: |
        docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/transformation:latest .
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/transformation:latest

    - name: Build and Push Load-SQL Image
      working-directory: ./load-sql
      run: |
        docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/load-sql:latest .
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/load-sql:latest

  deploy-to-aks:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to AKS
      uses: azure/aks-set-context@v2
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.AKS_CLUSTER }}

    - name: Deploy Kubernetes manifests
      working-directory: ./infrastructure
      run: |
        kubectl apply -f aks-deployment.yml